data = [
 {"id":1,"name":"Sled Pull","description":"1 set 10 minutes: Walk backwards with intention to push through your toes on each step. This is the lowest level for knees-over-toes training. Therefore, when you add load, the correct amount of weight is one that you can go for 10 minutes with your toes behind your knees on each step. If the load is too heavy, you may lean your weight back against it and avoid that position which is advantageous to help your feet, achilles, and knees.","image":"https://res.cloudinary.com/dt3ufyr9u/image/upload/v1691377542/sled-drag_bkwzmf.gif"},
 {"id":2,"name":"Tibialis Raises","description":"1 set 25 reps: Whether using the wall, double leg loading, single leg loading, the form is flexing the toes up, holding that strength then controlling back down. Difficulty increases with the wall by how far you stand And with equipment, it’s by how much you load. We have blood now in the front of the ankle. (Repeat after 1 set, 25 reps of Calf Raises)","image":"https://res.cloudinary.com/dt3ufyr9u/image/upload/v1691432696/tibialis-ezgif-2-5b7e2d8840_zytzbk.gif"},
 {"id":3,"name":"FHL Calf Raises","description":"1 set 25 reps: Step back until heels almost come up. Be at a full ankle bend and from that position, flex all the way trying to put the pressure on the big toe. If that’s too difficult, you can start as close to the wall, as you need, you can even use assistance at first. Once you can do your set comfortably, you’re then going to try to rebuild one leg at a time. That’s going to be more angle stretch and more strength on the way up","image":"https://res.cloudinary.com/dt3ufyr9u/image/upload/v1691387829/seated-calf-raise_dip3ty.gif"},
 {"id":4,"name":"KOT Calf Raises","description":"1 set 25 reps: standing closer to the wall, more like an arm’s length away and actually working on bending your knees. Shoulder to knee straight line, under the knee is all now strengthening and stretching through that bent ankle position. To make it easier, you can start with very little knee bend with your heels touching the floor. Once you can do the full set with your ankles off the floor, full ankle stretch, you would start rebuilding.","image":"https://res.cloudinary.com/dt3ufyr9u/image/upload/v1691388166/single-leg-standing-calf-raise_gkaqcy.gif"},
 {"id":5,"name":"Patrick Step","description":"1 set 25 reps: Before we get into this exercise, make sure you’re getting a full knees over toes, heels off Calf Raises so that your foot can handle the Patrick step pressure. Get a slight lean towards the wall so that you have balance and you’re not going to tip over, then, reach your heel to the floor by bending the opposite knee. Go down SLOWLY, it’s the going down. Control your heel to the floor.","image":"https://res.cloudinary.com/dt3ufyr9u/image/upload/v1691435748/Untitled_design_nw4oif.gif"},
 {"id":6,"name":"Split Squat","description":"5 sets, 5 reps: With something to balance and assist yourself, slowly bend your knee while staying on your back tippy toes and thinking about stretching your hip flexors at the same time.","image":"https://res.cloudinary.com/dt3ufyr9u/image/upload/v1691298594/atg-split-squat_fbyebw.gif"},
{
    "id": 7,
    "name": "couch stretch",
    "description": "back against wall, one knee bent, stretch psoas",
    "image": "https://res.cloudinary.com/dt3ufyr9u/image/upload/v1691432696/tibialis-ezgif-2-5b7e2d8840_zytzbk.gif",
}
]

